### PR TITLE
Fixes entity field term in state handler query

### LINKED ISSUE #9: Fix Download meta data querying
## Symptoms

In EDD Bookings, after loading the New Download page, the session lengths shown in the bookings metabox are not empty. They are actually session lengths from another Download (symptom 1).

This also happens when creating a new Download. Saving the session lengths also seems to save them to another Download (symptom 2).

## How to Reproduce

- Create a Download with some session lengths, if one does not already exist.
- Create a new Download.
- Observe symptom 1.
- Add some session lengths to the new Download and save.
- Open the previous Download Edit page
- Observe symptom 2

## Possible Cause

It seems like the meta data querying is broken.

After some investigation, it became apparent that the compiled `WP_Query` args where being incorrectly built. One of array keys is being generated as `"post.id"`. This is a result from an entity field term in the condition with the entity and field being `"post"` and `"id"` respectively.

This is happening because the args builder logic cannot detect that the entity field term is referencing a property of the "post" entity. It is configured to detect these properties from terms with the entity `"service"`.

## Recommended Solution

Modify resource model consumers such that they provide conditions with the correct entity name (`"service"`) in all entity field terms.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #9

### CODE REVIEW

**Review by XedinUnknown — APPROVED** [review]

**Comment by XedinUnknown** [comment]
@mecha, any way to centralize entity codes, like in constants or something?

**Comment by mecha** [comment]
Perhaps. The main module file ([`module.php`](https://github.com/RebelCode/rcmod-eddbk-services/blob/develop/module.php)) already declares some constants, but these are not ideal if other modules need the values as well. Perhaps config, but that might be too cumbersome for implementations. Some services already need 4 or more resource models.

**Comment by XedinUnknown** [comment]
@mecha, if module `B` needs entities, which are represented by CQRS models in module `A`, then maybe it's OK if `B` relies on constants declared in `A`. Where to declare them - that's another question. Thoughts?

**Comment by mecha** [comment]
The main module file is one option.

Alternatively, we can have the best of both words and declare the actual values in config, then have the module retrieve those config values on `run()` and declare the constants. This allows other modules to override the config values but also results in constants being available for use.

**Comment by XedinUnknown** [comment]
I'm not sure I feel good about declaring config constants on `run()`. Let's think about it some more.

https://github.com/orgs/RebelCode/projects/2#card-9933675

**Comment by mecha** [comment]
My main concern is allowing modules to override each other's configuration.A module might require altering the entity name, for instance.

Besides, it doesn't have to be directly in the `run()` method, just something that is invoked on `run()`.

**Pull request merged**
